// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evamanage.proto

package proto;

/**
 * Protobuf type {@code proto.EvaLogCondition}
 */
public  final class EvaLogCondition extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.EvaLogCondition)
    EvaLogConditionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EvaLogCondition.newBuilder() to construct.
  private EvaLogCondition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EvaLogCondition() {
    startTime_ = "";
    endTime_ = "";
    staffName_ = "";
    systemCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EvaLogCondition();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EvaLogCondition(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            startTime_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            endTime_ = s;
            break;
          }
          case 24: {

            pageIndex_ = input.readInt32();
            break;
          }
          case 32: {

            pageSize_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            staffName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            systemCode_ = s;
            break;
          }
          case 56: {

            type_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proto.Evamanage.internal_static_proto_EvaLogCondition_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proto.Evamanage.internal_static_proto_EvaLogCondition_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proto.EvaLogCondition.class, proto.EvaLogCondition.Builder.class);
  }

  public static final int STARTTIME_FIELD_NUMBER = 1;
  private volatile java.lang.Object startTime_;
  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>string StartTime = 1;</code>
   * @return The startTime.
   */
  public java.lang.String getStartTime() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startTime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>string StartTime = 1;</code>
   * @return The bytes for startTime.
   */
  public com.google.protobuf.ByteString
      getStartTimeBytes() {
    java.lang.Object ref = startTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENDTIME_FIELD_NUMBER = 2;
  private volatile java.lang.Object endTime_;
  /**
   * <pre>
   * 结束时间
   * </pre>
   *
   * <code>string EndTime = 2;</code>
   * @return The endTime.
   */
  public java.lang.String getEndTime() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      endTime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 结束时间
   * </pre>
   *
   * <code>string EndTime = 2;</code>
   * @return The bytes for endTime.
   */
  public com.google.protobuf.ByteString
      getEndTimeBytes() {
    java.lang.Object ref = endTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      endTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGEINDEX_FIELD_NUMBER = 3;
  private int pageIndex_;
  /**
   * <pre>
   * 当前第几页
   * </pre>
   *
   * <code>int32 PageIndex = 3;</code>
   * @return The pageIndex.
   */
  public int getPageIndex() {
    return pageIndex_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 4;
  private int pageSize_;
  /**
   * <pre>
   * 每页大小
   * </pre>
   *
   * <code>int32 PageSize = 4;</code>
   * @return The pageSize.
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int STAFFNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object staffName_;
  /**
   * <pre>
   *评价员工的name
   * </pre>
   *
   * <code>string StaffName = 5;</code>
   * @return The staffName.
   */
  public java.lang.String getStaffName() {
    java.lang.Object ref = staffName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      staffName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *评价员工的name
   * </pre>
   *
   * <code>string StaffName = 5;</code>
   * @return The bytes for staffName.
   */
  public com.google.protobuf.ByteString
      getStaffNameBytes() {
    java.lang.Object ref = staffName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      staffName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEMCODE_FIELD_NUMBER = 6;
  private volatile java.lang.Object systemCode_;
  /**
   * <pre>
   *系统编号
   * </pre>
   *
   * <code>string SystemCode = 6;</code>
   * @return The systemCode.
   */
  public java.lang.String getSystemCode() {
    java.lang.Object ref = systemCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      systemCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *系统编号
   * </pre>
   *
   * <code>string SystemCode = 6;</code>
   * @return The bytes for systemCode.
   */
  public com.google.protobuf.ByteString
      getSystemCodeBytes() {
    java.lang.Object ref = systemCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      systemCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 7;
  private int type_;
  /**
   * <pre>
   * 用户日志类型 0:查询所有 1：用户登录日志   2：用户登出日志
   * </pre>
   *
   * <code>int32 Type = 7;</code>
   * @return The type.
   */
  public int getType() {
    return type_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStartTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, startTime_);
    }
    if (!getEndTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, endTime_);
    }
    if (pageIndex_ != 0) {
      output.writeInt32(3, pageIndex_);
    }
    if (pageSize_ != 0) {
      output.writeInt32(4, pageSize_);
    }
    if (!getStaffNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, staffName_);
    }
    if (!getSystemCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, systemCode_);
    }
    if (type_ != 0) {
      output.writeInt32(7, type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStartTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, startTime_);
    }
    if (!getEndTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, endTime_);
    }
    if (pageIndex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, pageIndex_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, pageSize_);
    }
    if (!getStaffNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, staffName_);
    }
    if (!getSystemCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, systemCode_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proto.EvaLogCondition)) {
      return super.equals(obj);
    }
    proto.EvaLogCondition other = (proto.EvaLogCondition) obj;

    if (!getStartTime()
        .equals(other.getStartTime())) return false;
    if (!getEndTime()
        .equals(other.getEndTime())) return false;
    if (getPageIndex()
        != other.getPageIndex()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!getStaffName()
        .equals(other.getStaffName())) return false;
    if (!getSystemCode()
        .equals(other.getSystemCode())) return false;
    if (getType()
        != other.getType()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getStartTime().hashCode();
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + getEndTime().hashCode();
    hash = (37 * hash) + PAGEINDEX_FIELD_NUMBER;
    hash = (53 * hash) + getPageIndex();
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + STAFFNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStaffName().hashCode();
    hash = (37 * hash) + SYSTEMCODE_FIELD_NUMBER;
    hash = (53 * hash) + getSystemCode().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proto.EvaLogCondition parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.EvaLogCondition parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.EvaLogCondition parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.EvaLogCondition parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.EvaLogCondition parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proto.EvaLogCondition parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proto.EvaLogCondition parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.EvaLogCondition parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.EvaLogCondition parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proto.EvaLogCondition parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proto.EvaLogCondition parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proto.EvaLogCondition parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proto.EvaLogCondition prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.EvaLogCondition}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.EvaLogCondition)
      proto.EvaLogConditionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Evamanage.internal_static_proto_EvaLogCondition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Evamanage.internal_static_proto_EvaLogCondition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.EvaLogCondition.class, proto.EvaLogCondition.Builder.class);
    }

    // Construct using proto.EvaLogCondition.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startTime_ = "";

      endTime_ = "";

      pageIndex_ = 0;

      pageSize_ = 0;

      staffName_ = "";

      systemCode_ = "";

      type_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proto.Evamanage.internal_static_proto_EvaLogCondition_descriptor;
    }

    @java.lang.Override
    public proto.EvaLogCondition getDefaultInstanceForType() {
      return proto.EvaLogCondition.getDefaultInstance();
    }

    @java.lang.Override
    public proto.EvaLogCondition build() {
      proto.EvaLogCondition result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proto.EvaLogCondition buildPartial() {
      proto.EvaLogCondition result = new proto.EvaLogCondition(this);
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.pageIndex_ = pageIndex_;
      result.pageSize_ = pageSize_;
      result.staffName_ = staffName_;
      result.systemCode_ = systemCode_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proto.EvaLogCondition) {
        return mergeFrom((proto.EvaLogCondition)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proto.EvaLogCondition other) {
      if (other == proto.EvaLogCondition.getDefaultInstance()) return this;
      if (!other.getStartTime().isEmpty()) {
        startTime_ = other.startTime_;
        onChanged();
      }
      if (!other.getEndTime().isEmpty()) {
        endTime_ = other.endTime_;
        onChanged();
      }
      if (other.getPageIndex() != 0) {
        setPageIndex(other.getPageIndex());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (!other.getStaffName().isEmpty()) {
        staffName_ = other.staffName_;
        onChanged();
      }
      if (!other.getSystemCode().isEmpty()) {
        systemCode_ = other.systemCode_;
        onChanged();
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proto.EvaLogCondition parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proto.EvaLogCondition) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object startTime_ = "";
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>string StartTime = 1;</code>
     * @return The startTime.
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>string StartTime = 1;</code>
     * @return The bytes for startTime.
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>string StartTime = 1;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>string StartTime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = getDefaultInstance().getStartTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>string StartTime = 1;</code>
     * @param value The bytes for startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      startTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object endTime_ = "";
    /**
     * <pre>
     * 结束时间
     * </pre>
     *
     * <code>string EndTime = 2;</code>
     * @return The endTime.
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 结束时间
     * </pre>
     *
     * <code>string EndTime = 2;</code>
     * @return The bytes for endTime.
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 结束时间
     * </pre>
     *
     * <code>string EndTime = 2;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 结束时间
     * </pre>
     *
     * <code>string EndTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      
      endTime_ = getDefaultInstance().getEndTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 结束时间
     * </pre>
     *
     * <code>string EndTime = 2;</code>
     * @param value The bytes for endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      endTime_ = value;
      onChanged();
      return this;
    }

    private int pageIndex_ ;
    /**
     * <pre>
     * 当前第几页
     * </pre>
     *
     * <code>int32 PageIndex = 3;</code>
     * @return The pageIndex.
     */
    public int getPageIndex() {
      return pageIndex_;
    }
    /**
     * <pre>
     * 当前第几页
     * </pre>
     *
     * <code>int32 PageIndex = 3;</code>
     * @param value The pageIndex to set.
     * @return This builder for chaining.
     */
    public Builder setPageIndex(int value) {
      
      pageIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 当前第几页
     * </pre>
     *
     * <code>int32 PageIndex = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageIndex() {
      
      pageIndex_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <pre>
     * 每页大小
     * </pre>
     *
     * <code>int32 PageSize = 4;</code>
     * @return The pageSize.
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <pre>
     * 每页大小
     * </pre>
     *
     * <code>int32 PageSize = 4;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 每页大小
     * </pre>
     *
     * <code>int32 PageSize = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object staffName_ = "";
    /**
     * <pre>
     *评价员工的name
     * </pre>
     *
     * <code>string StaffName = 5;</code>
     * @return The staffName.
     */
    public java.lang.String getStaffName() {
      java.lang.Object ref = staffName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        staffName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *评价员工的name
     * </pre>
     *
     * <code>string StaffName = 5;</code>
     * @return The bytes for staffName.
     */
    public com.google.protobuf.ByteString
        getStaffNameBytes() {
      java.lang.Object ref = staffName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staffName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *评价员工的name
     * </pre>
     *
     * <code>string StaffName = 5;</code>
     * @param value The staffName to set.
     * @return This builder for chaining.
     */
    public Builder setStaffName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      staffName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *评价员工的name
     * </pre>
     *
     * <code>string StaffName = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearStaffName() {
      
      staffName_ = getDefaultInstance().getStaffName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *评价员工的name
     * </pre>
     *
     * <code>string StaffName = 5;</code>
     * @param value The bytes for staffName to set.
     * @return This builder for chaining.
     */
    public Builder setStaffNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      staffName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object systemCode_ = "";
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 6;</code>
     * @return The systemCode.
     */
    public java.lang.String getSystemCode() {
      java.lang.Object ref = systemCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        systemCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 6;</code>
     * @return The bytes for systemCode.
     */
    public com.google.protobuf.ByteString
        getSystemCodeBytes() {
      java.lang.Object ref = systemCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 6;</code>
     * @param value The systemCode to set.
     * @return This builder for chaining.
     */
    public Builder setSystemCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      systemCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemCode() {
      
      systemCode_ = getDefaultInstance().getSystemCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 6;</code>
     * @param value The bytes for systemCode to set.
     * @return This builder for chaining.
     */
    public Builder setSystemCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      systemCode_ = value;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <pre>
     * 用户日志类型 0:查询所有 1：用户登录日志   2：用户登出日志
     * </pre>
     *
     * <code>int32 Type = 7;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 用户日志类型 0:查询所有 1：用户登录日志   2：用户登出日志
     * </pre>
     *
     * <code>int32 Type = 7;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户日志类型 0:查询所有 1：用户登录日志   2：用户登出日志
     * </pre>
     *
     * <code>int32 Type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.EvaLogCondition)
  }

  // @@protoc_insertion_point(class_scope:proto.EvaLogCondition)
  private static final proto.EvaLogCondition DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proto.EvaLogCondition();
  }

  public static proto.EvaLogCondition getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EvaLogCondition>
      PARSER = new com.google.protobuf.AbstractParser<EvaLogCondition>() {
    @java.lang.Override
    public EvaLogCondition parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EvaLogCondition(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EvaLogCondition> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EvaLogCondition> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proto.EvaLogCondition getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

