// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evamanage.proto

package proto;

/**
 * Protobuf service {@code proto.EvaManageService}
 */
public  abstract class EvaManageService
    implements com.google.protobuf.Service {
  protected EvaManageService() {}

  public interface Interface {
    /**
     * <pre>
     *保存用户日志
     * </pre>
     *
     * <code>rpc SaveEvaUserLog(.proto.EvaUserLog) returns (.proto.EvaResult);</code>
     */
    public abstract void saveEvaUserLog(
        com.google.protobuf.RpcController controller,
        EvaUserLog request,
        com.google.protobuf.RpcCallback<EvaResult> done);

    /**
     * <pre>
     *查询用户日志
     * </pre>
     *
     * <code>rpc GetEvaUserLogs(.proto.EvaLogCondition) returns (.proto.EvaUserLogSearchData);</code>
     */
    public abstract void getEvaUserLogs(
        com.google.protobuf.RpcController controller,
        EvaLogCondition request,
        com.google.protobuf.RpcCallback<EvaUserLogSearchData> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new EvaManageService() {
      @Override
      public  void saveEvaUserLog(
          com.google.protobuf.RpcController controller,
          EvaUserLog request,
          com.google.protobuf.RpcCallback<EvaResult> done) {
        impl.saveEvaUserLog(controller, request, done);
      }

      @Override
      public  void getEvaUserLogs(
          com.google.protobuf.RpcController controller,
          EvaLogCondition request,
          com.google.protobuf.RpcCallback<EvaUserLogSearchData> done) {
        impl.getEvaUserLogs(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.saveEvaUserLog(controller, (EvaUserLog)request);
          case 1:
            return impl.getEvaUserLogs(controller, (EvaLogCondition)request);
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return EvaUserLog.getDefaultInstance();
          case 1:
            return EvaLogCondition.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return EvaResult.getDefaultInstance();
          case 1:
            return EvaUserLogSearchData.getDefaultInstance();
          default:
            throw new AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <pre>
   *保存用户日志
   * </pre>
   *
   * <code>rpc SaveEvaUserLog(.proto.EvaUserLog) returns (.proto.EvaResult);</code>
   */
  public abstract void saveEvaUserLog(
      com.google.protobuf.RpcController controller,
      EvaUserLog request,
      com.google.protobuf.RpcCallback<EvaResult> done);

  /**
   * <pre>
   *查询用户日志
   * </pre>
   *
   * <code>rpc GetEvaUserLogs(.proto.EvaLogCondition) returns (.proto.EvaUserLogSearchData);</code>
   */
  public abstract void getEvaUserLogs(
      com.google.protobuf.RpcController controller,
      EvaLogCondition request,
      com.google.protobuf.RpcCallback<EvaUserLogSearchData> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return Evamanage.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.saveEvaUserLog(controller, (EvaUserLog)request,
          com.google.protobuf.RpcUtil.<EvaResult>specializeCallback(
            done));
        return;
      case 1:
        this.getEvaUserLogs(controller, (EvaLogCondition)request,
          com.google.protobuf.RpcUtil.<EvaUserLogSearchData>specializeCallback(
            done));
        return;
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return EvaUserLog.getDefaultInstance();
      case 1:
        return EvaLogCondition.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return EvaResult.getDefaultInstance();
      case 1:
        return EvaUserLogSearchData.getDefaultInstance();
      default:
        throw new AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends EvaManageService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void saveEvaUserLog(
        com.google.protobuf.RpcController controller,
        EvaUserLog request,
        com.google.protobuf.RpcCallback<EvaResult> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        EvaResult.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          EvaResult.class,
          EvaResult.getDefaultInstance()));
    }

    public  void getEvaUserLogs(
        com.google.protobuf.RpcController controller,
        EvaLogCondition request,
        com.google.protobuf.RpcCallback<EvaUserLogSearchData> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        EvaUserLogSearchData.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          EvaUserLogSearchData.class,
          EvaUserLogSearchData.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public EvaResult saveEvaUserLog(
        com.google.protobuf.RpcController controller,
        EvaUserLog request)
        throws com.google.protobuf.ServiceException;

    public EvaUserLogSearchData getEvaUserLogs(
        com.google.protobuf.RpcController controller,
        EvaLogCondition request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public EvaResult saveEvaUserLog(
        com.google.protobuf.RpcController controller,
        EvaUserLog request)
        throws com.google.protobuf.ServiceException {
      return (EvaResult) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        EvaResult.getDefaultInstance());
    }


    public EvaUserLogSearchData getEvaUserLogs(
        com.google.protobuf.RpcController controller,
        EvaLogCondition request)
        throws com.google.protobuf.ServiceException {
      return (EvaUserLogSearchData) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        EvaUserLogSearchData.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:proto.EvaManageService)
}

