// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evamanage.proto

package proto;

/**
 * Protobuf type {@code proto.EvaUserLog}
 */
public  final class EvaUserLog extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.EvaUserLog)
    EvaUserLogOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EvaUserLog.newBuilder() to construct.
  private EvaUserLog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EvaUserLog() {
    name_ = "";
    role_ = "";
    ip_ = "";
    createAt_ = "";
    staffId_ = "";
    staffName_ = "";
    systemCode_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new EvaUserLog();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EvaUserLog(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            role_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            createAt_ = s;
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            staffId_ = s;
            break;
          }
          case 58: {
            String s = input.readStringRequireUtf8();

            staffName_ = s;
            break;
          }
          case 66: {
            String s = input.readStringRequireUtf8();

            systemCode_ = s;
            break;
          }
          case 72: {

            type_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Evamanage.internal_static_proto_EvaUserLog_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Evamanage.internal_static_proto_EvaUserLog_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            EvaUserLog.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 Id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile Object name_;
  /**
   * <code>string Name = 2;</code>
   * @return The name.
   */
  public String getName() {
    Object ref = name_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string Name = 2;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    Object ref = name_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLE_FIELD_NUMBER = 3;
  private volatile Object role_;
  /**
   * <code>string Role = 3;</code>
   * @return The role.
   */
  public String getRole() {
    Object ref = role_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      role_ = s;
      return s;
    }
  }
  /**
   * <code>string Role = 3;</code>
   * @return The bytes for role.
   */
  public com.google.protobuf.ByteString
      getRoleBytes() {
    Object ref = role_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      role_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IP_FIELD_NUMBER = 4;
  private volatile Object ip_;
  /**
   * <code>string Ip = 4;</code>
   * @return The ip.
   */
  public String getIp() {
    Object ref = ip_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string Ip = 4;</code>
   * @return The bytes for ip.
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    Object ref = ip_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEAT_FIELD_NUMBER = 5;
  private volatile Object createAt_;
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateAt = 5;</code>
   * @return The createAt.
   */
  public String getCreateAt() {
    Object ref = createAt_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createAt_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateAt = 5;</code>
   * @return The bytes for createAt.
   */
  public com.google.protobuf.ByteString
      getCreateAtBytes() {
    Object ref = createAt_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      createAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAFFID_FIELD_NUMBER = 6;
  private volatile Object staffId_;
  /**
   * <pre>
   *用户ID
   * </pre>
   *
   * <code>string StaffId = 6;</code>
   * @return The staffId.
   */
  public String getStaffId() {
    Object ref = staffId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      staffId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户ID
   * </pre>
   *
   * <code>string StaffId = 6;</code>
   * @return The bytes for staffId.
   */
  public com.google.protobuf.ByteString
      getStaffIdBytes() {
    Object ref = staffId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      staffId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAFFNAME_FIELD_NUMBER = 7;
  private volatile Object staffName_;
  /**
   * <pre>
   *用户姓名
   * </pre>
   *
   * <code>string StaffName = 7;</code>
   * @return The staffName.
   */
  public String getStaffName() {
    Object ref = staffName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      staffName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *用户姓名
   * </pre>
   *
   * <code>string StaffName = 7;</code>
   * @return The bytes for staffName.
   */
  public com.google.protobuf.ByteString
      getStaffNameBytes() {
    Object ref = staffName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      staffName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYSTEMCODE_FIELD_NUMBER = 8;
  private volatile Object systemCode_;
  /**
   * <pre>
   *系统编号
   * </pre>
   *
   * <code>string SystemCode = 8;</code>
   * @return The systemCode.
   */
  public String getSystemCode() {
    Object ref = systemCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      systemCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *系统编号
   * </pre>
   *
   * <code>string SystemCode = 8;</code>
   * @return The bytes for systemCode.
   */
  public com.google.protobuf.ByteString
      getSystemCodeBytes() {
    Object ref = systemCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      systemCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 9;
  private int type_;
  /**
   * <pre>
   * 用户日志类型 1：用户登录日志   2：用户登出日志
   * </pre>
   *
   * <code>int32 Type = 9;</code>
   * @return The type.
   */
  public int getType() {
    return type_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getRoleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, role_);
    }
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ip_);
    }
    if (!getCreateAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, createAt_);
    }
    if (!getStaffIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, staffId_);
    }
    if (!getStaffNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, staffName_);
    }
    if (!getSystemCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, systemCode_);
    }
    if (type_ != 0) {
      output.writeInt32(9, type_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getRoleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, role_);
    }
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ip_);
    }
    if (!getCreateAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, createAt_);
    }
    if (!getStaffIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, staffId_);
    }
    if (!getStaffNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, staffName_);
    }
    if (!getSystemCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, systemCode_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof EvaUserLog)) {
      return super.equals(obj);
    }
    EvaUserLog other = (EvaUserLog) obj;

    if (getId()
        != other.getId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getRole()
        .equals(other.getRole())) return false;
    if (!getIp()
        .equals(other.getIp())) return false;
    if (!getCreateAt()
        .equals(other.getCreateAt())) return false;
    if (!getStaffId()
        .equals(other.getStaffId())) return false;
    if (!getStaffName()
        .equals(other.getStaffName())) return false;
    if (!getSystemCode()
        .equals(other.getSystemCode())) return false;
    if (getType()
        != other.getType()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ROLE_FIELD_NUMBER;
    hash = (53 * hash) + getRole().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
    hash = (53 * hash) + getCreateAt().hashCode();
    hash = (37 * hash) + STAFFID_FIELD_NUMBER;
    hash = (53 * hash) + getStaffId().hashCode();
    hash = (37 * hash) + STAFFNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStaffName().hashCode();
    hash = (37 * hash) + SYSTEMCODE_FIELD_NUMBER;
    hash = (53 * hash) + getSystemCode().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static EvaUserLog parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EvaUserLog parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EvaUserLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EvaUserLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EvaUserLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static EvaUserLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static EvaUserLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EvaUserLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static EvaUserLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static EvaUserLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static EvaUserLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static EvaUserLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(EvaUserLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.EvaUserLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.EvaUserLog)
      EvaUserLogOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Evamanage.internal_static_proto_EvaUserLog_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Evamanage.internal_static_proto_EvaUserLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EvaUserLog.class, Builder.class);
    }

    // Construct using proto.EvaUserLog.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      name_ = "";

      role_ = "";

      ip_ = "";

      createAt_ = "";

      staffId_ = "";

      staffName_ = "";

      systemCode_ = "";

      type_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Evamanage.internal_static_proto_EvaUserLog_descriptor;
    }

    @Override
    public EvaUserLog getDefaultInstanceForType() {
      return EvaUserLog.getDefaultInstance();
    }

    @Override
    public EvaUserLog build() {
      EvaUserLog result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public EvaUserLog buildPartial() {
      EvaUserLog result = new EvaUserLog(this);
      result.id_ = id_;
      result.name_ = name_;
      result.role_ = role_;
      result.ip_ = ip_;
      result.createAt_ = createAt_;
      result.staffId_ = staffId_;
      result.staffName_ = staffName_;
      result.systemCode_ = systemCode_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof EvaUserLog) {
        return mergeFrom((EvaUserLog)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(EvaUserLog other) {
      if (other == EvaUserLog.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getRole().isEmpty()) {
        role_ = other.role_;
        onChanged();
      }
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (!other.getCreateAt().isEmpty()) {
        createAt_ = other.createAt_;
        onChanged();
      }
      if (!other.getStaffId().isEmpty()) {
        staffId_ = other.staffId_;
        onChanged();
      }
      if (!other.getStaffName().isEmpty()) {
        staffName_ = other.staffName_;
        onChanged();
      }
      if (!other.getSystemCode().isEmpty()) {
        systemCode_ = other.systemCode_;
        onChanged();
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      EvaUserLog parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (EvaUserLog) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 Id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 Id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 Id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private Object name_ = "";
    /**
     * <code>string Name = 2;</code>
     * @return The name.
     */
    public String getName() {
      Object ref = name_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string Name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private Object role_ = "";
    /**
     * <code>string Role = 3;</code>
     * @return The role.
     */
    public String getRole() {
      Object ref = role_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        role_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Role = 3;</code>
     * @return The bytes for role.
     */
    public com.google.protobuf.ByteString
        getRoleBytes() {
      Object ref = role_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        role_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Role = 3;</code>
     * @param value The role to set.
     * @return This builder for chaining.
     */
    public Builder setRole(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      role_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Role = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRole() {
      
      role_ = getDefaultInstance().getRole();
      onChanged();
      return this;
    }
    /**
     * <code>string Role = 3;</code>
     * @param value The bytes for role to set.
     * @return This builder for chaining.
     */
    public Builder setRoleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      role_ = value;
      onChanged();
      return this;
    }

    private Object ip_ = "";
    /**
     * <code>string Ip = 4;</code>
     * @return The ip.
     */
    public String getIp() {
      Object ref = ip_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Ip = 4;</code>
     * @return The bytes for ip.
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Ip = 4;</code>
     * @param value The ip to set.
     * @return This builder for chaining.
     */
    public Builder setIp(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Ip = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>string Ip = 4;</code>
     * @param value The bytes for ip to set.
     * @return This builder for chaining.
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private Object createAt_ = "";
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateAt = 5;</code>
     * @return The createAt.
     */
    public String getCreateAt() {
      Object ref = createAt_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createAt_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateAt = 5;</code>
     * @return The bytes for createAt.
     */
    public com.google.protobuf.ByteString
        getCreateAtBytes() {
      Object ref = createAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateAt = 5;</code>
     * @param value The createAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreateAt(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateAt = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateAt() {
      
      createAt_ = getDefaultInstance().getCreateAt();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string CreateAt = 5;</code>
     * @param value The bytes for createAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreateAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createAt_ = value;
      onChanged();
      return this;
    }

    private Object staffId_ = "";
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>string StaffId = 6;</code>
     * @return The staffId.
     */
    public String getStaffId() {
      Object ref = staffId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        staffId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>string StaffId = 6;</code>
     * @return The bytes for staffId.
     */
    public com.google.protobuf.ByteString
        getStaffIdBytes() {
      Object ref = staffId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        staffId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>string StaffId = 6;</code>
     * @param value The staffId to set.
     * @return This builder for chaining.
     */
    public Builder setStaffId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      staffId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>string StaffId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearStaffId() {
      
      staffId_ = getDefaultInstance().getStaffId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户ID
     * </pre>
     *
     * <code>string StaffId = 6;</code>
     * @param value The bytes for staffId to set.
     * @return This builder for chaining.
     */
    public Builder setStaffIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      staffId_ = value;
      onChanged();
      return this;
    }

    private Object staffName_ = "";
    /**
     * <pre>
     *用户姓名
     * </pre>
     *
     * <code>string StaffName = 7;</code>
     * @return The staffName.
     */
    public String getStaffName() {
      Object ref = staffName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        staffName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *用户姓名
     * </pre>
     *
     * <code>string StaffName = 7;</code>
     * @return The bytes for staffName.
     */
    public com.google.protobuf.ByteString
        getStaffNameBytes() {
      Object ref = staffName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        staffName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *用户姓名
     * </pre>
     *
     * <code>string StaffName = 7;</code>
     * @param value The staffName to set.
     * @return This builder for chaining.
     */
    public Builder setStaffName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      staffName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户姓名
     * </pre>
     *
     * <code>string StaffName = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStaffName() {
      
      staffName_ = getDefaultInstance().getStaffName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *用户姓名
     * </pre>
     *
     * <code>string StaffName = 7;</code>
     * @param value The bytes for staffName to set.
     * @return This builder for chaining.
     */
    public Builder setStaffNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      staffName_ = value;
      onChanged();
      return this;
    }

    private Object systemCode_ = "";
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 8;</code>
     * @return The systemCode.
     */
    public String getSystemCode() {
      Object ref = systemCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        systemCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 8;</code>
     * @return The bytes for systemCode.
     */
    public com.google.protobuf.ByteString
        getSystemCodeBytes() {
      Object ref = systemCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        systemCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 8;</code>
     * @param value The systemCode to set.
     * @return This builder for chaining.
     */
    public Builder setSystemCode(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      systemCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearSystemCode() {
      
      systemCode_ = getDefaultInstance().getSystemCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *系统编号
     * </pre>
     *
     * <code>string SystemCode = 8;</code>
     * @param value The bytes for systemCode to set.
     * @return This builder for chaining.
     */
    public Builder setSystemCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      systemCode_ = value;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <pre>
     * 用户日志类型 1：用户登录日志   2：用户登出日志
     * </pre>
     *
     * <code>int32 Type = 9;</code>
     * @return The type.
     */
    public int getType() {
      return type_;
    }
    /**
     * <pre>
     * 用户日志类型 1：用户登录日志   2：用户登出日志
     * </pre>
     *
     * <code>int32 Type = 9;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 用户日志类型 1：用户登录日志   2：用户登出日志
     * </pre>
     *
     * <code>int32 Type = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.EvaUserLog)
  }

  // @@protoc_insertion_point(class_scope:proto.EvaUserLog)
  private static final EvaUserLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new EvaUserLog();
  }

  public static EvaUserLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EvaUserLog>
      PARSER = new com.google.protobuf.AbstractParser<EvaUserLog>() {
    @Override
    public EvaUserLog parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EvaUserLog(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EvaUserLog> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<EvaUserLog> getParserForType() {
    return PARSER;
  }

  @Override
  public EvaUserLog getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

