// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evamanage.proto

package proto;

public interface EvaUserLogOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EvaUserLog)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 Id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string Name = 2;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string Name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string Role = 3;</code>
   * @return The role.
   */
  String getRole();
  /**
   * <code>string Role = 3;</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string Ip = 4;</code>
   * @return The ip.
   */
  String getIp();
  /**
   * <code>string Ip = 4;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateAt = 5;</code>
   * @return The createAt.
   */
  String getCreateAt();
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string CreateAt = 5;</code>
   * @return The bytes for createAt.
   */
  com.google.protobuf.ByteString
      getCreateAtBytes();

  /**
   * <pre>
   *用户ID
   * </pre>
   *
   * <code>string StaffId = 6;</code>
   * @return The staffId.
   */
  String getStaffId();
  /**
   * <pre>
   *用户ID
   * </pre>
   *
   * <code>string StaffId = 6;</code>
   * @return The bytes for staffId.
   */
  com.google.protobuf.ByteString
      getStaffIdBytes();

  /**
   * <pre>
   *用户姓名
   * </pre>
   *
   * <code>string StaffName = 7;</code>
   * @return The staffName.
   */
  String getStaffName();
  /**
   * <pre>
   *用户姓名
   * </pre>
   *
   * <code>string StaffName = 7;</code>
   * @return The bytes for staffName.
   */
  com.google.protobuf.ByteString
      getStaffNameBytes();

  /**
   * <pre>
   *系统编号
   * </pre>
   *
   * <code>string SystemCode = 8;</code>
   * @return The systemCode.
   */
  String getSystemCode();
  /**
   * <pre>
   *系统编号
   * </pre>
   *
   * <code>string SystemCode = 8;</code>
   * @return The bytes for systemCode.
   */
  com.google.protobuf.ByteString
      getSystemCodeBytes();

  /**
   * <pre>
   * 用户日志类型 1：用户登录日志   2：用户登出日志
   * </pre>
   *
   * <code>int32 Type = 9;</code>
   * @return The type.
   */
  int getType();
}
